### ISSUE TITLE
[PE-D][Tester A] Auxillery Command exit doesnt work in categories in the contact function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W14-2/tp#167]
**Steps to reproduce**

1

category

exit

**Expected outcome**

It should exit out of the categories section but it doesnt not.

**Actual Outcome**

"Invalid Command" an error message is thrown instead

**Screenshot**

![issue 4.png](https://raw.githubusercontent.com/Atulteja/ped/main/files/3b8d72de-2038-4eda-9fde-7ae28531891d.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Atulteja/ped#4

**Comment by C2linaung** [comment]
This user really cannot follow the guide. But, do look into changing the command to exit the category mode for the contact manager.  I think we are using a different command. BETTER TO USE SAME to prevent this sort of confusion from user side
