### ISSUE TITLE
[PE-D][Tester A] Deleting an expense with the month tag does not work

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W14-2/tp#180]
**Steps to reproduce**

2

add /month: 2024-11 /name: spotify /cost: 10

delete 1 /month: 2024-11

**Expected outcome**

The entry in index 1 should be deleted

**Actual Outcome**

'Invalid Index!" although i use the same command input format as shown in the UG

**Screenshot**

Command line:
![image.png](https://raw.githubusercontent.com/Atulteja/ped/main/files/35586ef9-393e-457a-9c11-5f7b7bb9659e.png)

UG:
![image.png](https://raw.githubusercontent.com/Atulteja/ped/main/files/9ad26a2d-3c56-4013-a68f-7133e50913a9.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Atulteja/ped#8

**Comment by C2linaung** [comment]
VERY VALID FLAW.

I have checked what was going on. The user here used an additonal space character after the month tag here, which caused the error to occur.
